---
apiVersion: build.tanzu.vmware.com/v1
kind: ContainerAppBuildPlan
metadata:
  name: simple.tanzu.vmware.com
spec:
  registry: ""
  buildpacks:
    builder: "paketobuildpacks/builder-jammy-base"
  postBuildSteps:
    - name: tanzu-spring-boot-config
      namedTask: tanzu-spring-boot
    # - name: add-env
    #   containerTask:
    #     image: tomkennedy73/container-app-modifier
    #     args: ["SOME-ENV-NAME=SOME-ENV-VALUE"]
  runtimes:
    - name: kubernetes-carvel-package
      description: Create a carvel package for deploying on kubernetes
      steps:
        - name: generate kubernetes yaml
          namedTask: tanzu-kubernetes-deployment
        - name: create carvel package
          namedTask: tanzu-kubernetes-carvel-package
    - name: kubernetes-plain
      description: Create kubernetes yaml files for deploying on kubernetes
      steps:
        - name: generate kubernetes yaml
          namedTask: tanzu-kubernetes-deployment
    - name: container-image
      description: write image to file for use with container runtime (i.e docker run)
      steps:
        - name: write image
          namedTask: tanzu-container-image

