apiVersion: build.tanzu.vmware.com/v1
kind: ContainerAppBuildPlan
metadata:
  name: platform-config
spec:
  registry: ""
  nonSecretEnv:
  - name: FOO
    value: bar
  buildpacks:
    builder: "paketobuildpacks/builder-jammy-base"
  postBuildSteps:
  - name: apply-spring-boot-conventions
    namedTask: tanzu-spring-boot
  - name: add-env
    containerTask:
      image: tomkennedy73/container-app-modifier
      args: ["SOME-ENV-NAME=SOME-ENV-VALUE"]
