apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: single-image-single-app
spec:
  build:
    path: "../.."
  ports:
    - name: main
      port: 8080
  nonSecretEnv:
    - name: PORT
      value: "8080"

