apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: api-gateway
spec:
  build:
    path: "../../where-for-dinner-api-gateway"
    nonSecretEnv:
      - name: BP_JVM_VERSION
        value: "21"
