apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: availability
spec:
  build:
    path: "../../where-for-dinner-availability"
    nonSecretEnv:
      - name: BP_JVM_VERSION
        value: "21"
