apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: notify
spec:
  build:
    path: "where-for-dinner-src//where-for-dinner-notify"
    nonSecretEnv:
      - name: BP_JVM_VERSION
        value: "21"
